### List of largest companies in the United States by revenue

In [1]:
from bs4 import BeautifulSoup  
import pandas as pd 
import requests

In [2]:
url = "https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue"

# Add headers with a proper User-Agent
headers = {
"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"}

page = requests.get(url, headers=headers)

In [3]:
soup = BeautifulSoup(page.text, "html.parser")

In [4]:
table = soup.find_all('table')[0]

In [5]:
print(table.prettify())

<table class="wikitable sortable">
 <caption>
 </caption>
 <tbody>
  <tr>
   <th>
    Rank
   </th>
   <th>
    Name
   </th>
   <th>
    Industry
   </th>
   <th>
    Revenue
    <br/>
    (USD millions)
   </th>
   <th>
    Revenue growth
   </th>
   <th>
    Employees
   </th>
   <th>
    Headquarters
   </th>
  </tr>
  <tr>
   <td>
    1
   </td>
   <td>
    <a href="/wiki/Walmart" title="Walmart">
     Walmart
    </a>
   </td>
   <td>
    Retail
   </td>
   <td style="text-align:center;">
    680,985
   </td>
   <td style="text-align:center;">
    <span typeof="mw:File">
     <span title="Increase">
      <img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/>
     </span>
    </span>
    <span data-sort-value="7000300000000000000♠" style="display:none">
    </span>
    5.1%
   </td>
   <td style="text-align:center;">
    2,100,000
   </td>
   <td>
    <a href="/wiki/Bentonville,_Arkansas" title="Bentonville, Arkansas">
     Bentonville, Arkansas
    </a>
   </td>
  </tr>
  <tr>
   <td>
    2
   </td>
   <td>
    <a href="/wiki/Amazon_(company)" title="Amazon (company)">
     Amazon
    </a>
   </td>
   <td>
    Retail and cloud computing
   </td>
   <td style="text-align:center;">
    637,959
   </td>
   <td style="text-align:center;">
    <span typeof="mw:File">
     <span title="Increase">
      <img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/>
     </span>
    </span>
    <span data-sort-value="7000300000000000000♠" style="display:none">
    </span>
    11.0%
   </td>
   <td style="text-align:center;">
    1,556,000
   </td>
   <td>
    <a href="/wiki/Seattle" title="Seattle">
     Seattle, Washington
    </a>
   </td>
  </tr>
  <tr>
   <td>
    3
   </td>
   <td>
    <a href="/wiki/UnitedHealth_Group" title="UnitedHealth Group">
     UnitedHealth Group
    </a>
   </td>
   <td>
    Healthcare
   </td>
   <td style="text-align:center;">
    400,278
   </td>
   <td style="text-align:center;">
    <span typeof="mw:File">
     <span title="Increase">
      <img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/>
     </span>
    </span>
    <span data-sort-value="7000300000000000000♠" style="display:none">
    </span>
    7.7%
   </td>
   <td style="text-align:center;">
    400,000
   </td>
   <td>
    <a href="/wiki/Minnetonka,_Minnesota" title="Minnetonka, Minnesota">
     Minnetonka, Minnesota
    </a>
   </td>
  </tr>
  <tr>
   <td>
    4
   </td>
   <td>
    <a class="mw-redirect" href="/wiki/Apple_Inc" title="Apple Inc">
     Apple
    </a>
   </td>
   <td>
    Technology
   </td>
   <td style="text-align:center;">
    391,035
   </td>
   <td style="text-align:center;">
    <span typeof="mw:File">
     <span title="Increase">
      <img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/>
     </span>
    </span>
    <span data-sort-value="7000300000000000000♠" style="display:none">
    </span>
    2.0%
   </td>
   <td style="text-align:center;">
    164,000
   </td>
   <td>
    <a href="/wiki/Cupertino,_California" title="Cupertino, California">
     Cupertino, California
    </a>
   </td>
  </tr>
  <tr>
   <td>
    5
   </td>
   <td>
    <a href="/wiki/CVS_Health" title="CVS Health">
     CVS Health
    </a>
   </td>
   <td>
    Healthcare
   </td>
   <td style="text-align:center;">
    372,809
   </td>
   <td style="text-align:center;">
    <span typeof="mw:File">
     <span title="Increase">
      <img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/>
     </span>
    </span>
    <span data-sort-value="7000300000000000000♠" style="display:none">
    </span>
    4.2%
   </td>
   <td style="text-align:center;">
    259,500
   </td>
   <td>
    <a href="/wiki/Woonsocket,_Rhode_Island" title="Woonsocket, Rhode Island">
     Woonsocket, Rhode Island
    </a>
   </td>
  </tr>
  <tr>
   <td>
    6
   </td>
   <td>
    <a href="/wiki/Berkshire_Hathaway" title="Berkshire Hathaway">
     Berkshire Hathaway
    </a>
   </td>
   <td>
    Conglomerate
   </td>
   <td style="text-align:center;">
    371,433
   </td>
   <td style="text-align:center;">
    <span typeof="mw:File">
     <span title="Increase">
      <img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/>
     </span>
    </span>
    <span data-sort-value="7000300000000000000♠" style="display:none">
    </span>
    1.9%
   </td>
   <td style="text-align:center;">
    392,400
   </td>
   <td>
    <a href="/wiki/Omaha,_Nebraska" title="Omaha, Nebraska">
     Omaha, Nebraska
    </a>
   </td>
  </tr>
  <tr>
   <td>
    7
   </td>
   <td>
    <a class="mw-redirect" href="/wiki/Alphabet_Inc" title="Alphabet Inc">
     Alphabet
    </a>
   </td>
   <td>
    Technology and cloud computing
   </td>
   <td style="text-align:center;">
    350,018
   </td>
   <td style="text-align:center;">
    <span typeof="mw:File">
     <span title="Increase">
      <img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/>
     </span>
    </span>
    <span data-sort-value="7000300000000000000♠" style="display:none">
    </span>
    13.9%
   </td>
   <td style="text-align:center;">
    183,323
   </td>
   <td>
    <a href="/wiki/Mountain_View,_California" title="Mountain View, California">
     Mountain View, California
    </a>
   </td>
  </tr>
  <tr>
   <td>
    8
   </td>
   <td>
    <a href="/wiki/ExxonMobil" title="ExxonMobil">
     Exxon Mobil
    </a>
   </td>
   <td>
    Petroleum
   </td>
   <td style="text-align:center;">
    349,595
   </td>
   <td style="text-align:center;">
    <span typeof="mw:File">
     <span title="Increase">
      <img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/>
     </span>
    </span>
    <span data-sort-value="7000300000000000000♠" style="display:none">
    </span>
    1.5%
   </td>
   <td style="text-align:center;">
    60,900
   </td>
   <td>
    <a href="/wiki/Spring,_Texas" title="Spring, Texas">
     Spring, Texas
    </a>
   </td>
  </tr>
  <tr>
   <td>
    9
   </td>
   <td>
    <a href="/wiki/McKesson_Corporation" title="McKesson Corporation">
     McKesson Corporation
    </a>
   </td>
   <td>
    Healthcare
   </td>
   <td style="text-align:center;">
    308,951
   </td>
   <td style="text-align:center;">
    <span typeof="mw:File">
     <span title="Increase">
      <img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/>
     </span>
    </span>
    <span data-sort-value="7000300000000000000♠" style="display:none">
    </span>
    11.7%
   </td>
   <td style="text-align:center;">
    48,000
   </td>
   <td>
    <a href="/wiki/Irving,_Texas" title="Irving, Texas">
     Irving, Texas
    </a>
   </td>
  </tr>
  <tr>
   <td>
    10
   </td>
   <td>
    <a href="/wiki/Cencora" title="Cencora">
     Cencora
    </a>
   </td>
   <td>
    Pharmacy wholesale
   </td>
   <td style="text-align:center;">
    293,959
   </td>
   <td style="text-align:center;">
    <span typeof="mw:File">
     <span title="Increase">
      <img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/>
     </span>
    </span>
    <span data-sort-value="7000300000000000000♠" style="display:none">
    </span>
    12.1%
   </td>
   <td style="text-align:center;">
    44,000
   </td>
   <td>
    <a href="/wiki/Conshohocken,_Pennsylvania" title="Conshohocken, Pennsylvania">
     Conshohocken, Pennsylvania
    </a>
   </td>
  </tr>
  <tr>
   <td>
    11
   </td>
   <td>
    <a href="/wiki/JPMorgan_Chase" title="JPMorgan Chase">
     JPMorgan Chase
    </a>
   </td>
   <td>
    Financials
   </td>
   <td style="text-align:center;">
    278,906
   </td>
   <td style="text-align:center;">
    <span typeof="mw:File">
     <span title="Increase">
      <img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/>
     </span>
    </span>
    <span data-sort-value="7000300000000000000♠" style="display:none">
    </span>
    16.5%
   </td>
   <td style="text-align:center;">
    317,233
   </td>
   <td>
    <a href="/wiki/New_York_City" title="New York City">
     New York City, New York
    </a>
   </td>
  </tr>
  <tr>
   <td>
    12
   </td>
   <td>
    <a href="/wiki/Costco" title="Costco">
     Costco Wholesale
    </a>
   </td>
   <td>
    Retail
   </td>
   <td style="text-align:center;">
    254,453
   </td>
   <td style="text-align:center;">
    <span typeof="mw:File">
     <span title="Increase">
      <img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/>
     </span>
    </span>
    <span data-sort-value="7000300000000000000♠" style="display:none">
    </span>
    5.0%
   </td>
   <td style="text-align:center;">
    333,000
   </td>
   <td>
    <a href="/wiki/Issaquah,_Washington" title="Issaquah, Washington">
     Issaquah, Washington
    </a>
   </td>
  </tr>
  <tr>
   <td>
    13
   </td>
   <td>
    <a class="mw-redirect" href="/wiki/Cigna" title="Cigna">
     Cigna
    </a>
   </td>
   <td>
    Health insurance
   </td>
   <td style="text-align:center;">
    247,121
   </td>
   <td style="text-align:center;">
    <span typeof="mw:File">
     <span title="Increase">
      <img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/>
     </span>
    </span>
    <span data-sort-value="7000300000000000000♠" style="display:none">
    </span>
    26.6%
   </td>
   <td style="text-align:center;">
    72,398
   </td>
   <td>
    <a href="/wiki/Bloomfield,_Connecticut" title="Bloomfield, Connecticut">
     Bloomfield, Connecticut
    </a>
   </td>
  </tr>
  <tr>
   <td>
    14
   </td>
   <td>
    <a href="/wiki/Microsoft" title="Microsoft">
     Microsoft
    </a>
   </td>
   <td>
    Technology and cloud computing
   </td>
   <td style="text-align:center;">
    245,122
   </td>
   <td style="text-align:center;">
    <span typeof="mw:File">
     <span title="Increase">
      <img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/>
     </span>
    </span>
    <span data-sort-value="7000300000000000000♠" style="display:none">
    </span>
    15.7%
   </td>
   <td style="text-align:center;">
    228,000
   </td>
   <td>
    <a href="/wiki/Redmond,_Washington" title="Redmond, Washington">
     Redmond, Washington
    </a>
   </td>
  </tr>
  <tr>
   <td>
    15
   </td>
   <td>
    <a href="/wiki/Cardinal_Health" title="Cardinal Health">
     Cardinal Health
    </a>
   </td>
   <td>
    Healthcare
   </td>
   <td style="text-align:center;">
    226,827
   </td>
   <td style="text-align:center;">
    <span typeof="mw:File">
     <span title="Increase">
      <img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/>
     </span>
    </span>
    <span data-sort-value="7000300000000000000♠" style="display:none">
    </span>
    10.6%
   </td>
   <td style="text-align:center;">
    48,411
   </td>
   <td>
    <a href="/wiki/Dublin,_Ohio" title="Dublin, Ohio">
     Dublin, Ohio
    </a>
   </td>
  </tr>
  <tr>
   <td>
    16
   </td>
   <td>
    <a href="/wiki/Chevron_Corporation" title="Chevron Corporation">
     Chevron
    </a>
   </td>
   <td>
    Petroleum
   </td>
   <td style="text-align:center;">
    202,792
   </td>
   <td style="text-align:center;">
    <span typeof="mw:File">
     <span title="Increase">
      <img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/>
     </span>
    </span>
    <span data-sort-value="7000300000000000000♠" style="display:none">
    </span>
    0.9%
   </td>
   <td style="text-align:center;">
    45,298
   </td>
   <td>
    <a class="mw-redirect" href="/wiki/Houston,_Texas" title="Houston, Texas">
     Houston, Texas
    </a>
   </td>
  </tr>
  <tr>
   <td>
    17
   </td>
   <td>
    <a href="/wiki/Bank_of_America" title="Bank of America">
     Bank of America
    </a>
   </td>
   <td>
    Financials
   </td>
   <td style="text-align:center;">
    192,434
   </td>
   <td style="text-align:center;">
    <span typeof="mw:File">
     <span title="Increase">
      <img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/>
     </span>
    </span>
    <span data-sort-value="7000300000000000000♠" style="display:none">
    </span>
    11.9%
   </td>
   <td style="text-align:center;">
    213,193
   </td>
   <td>
    <a href="/wiki/Charlotte,_North_Carolina" title="Charlotte, North Carolina">
     Charlotte, North Carolina
    </a>
   </td>
  </tr>
  <tr>
   <td>
    18
   </td>
   <td>
    <a href="/wiki/General_Motors" title="General Motors">
     General Motors
    </a>
   </td>
   <td>
    Automotive
   </td>
   <td style="text-align:center;">
    187,442
   </td>
   <td style="text-align:center;">
    <span typeof="mw:File">
     <span title="Increase">
      <img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/>
     </span>
    </span>
    <span data-sort-value="7000300000000000000♠" style="display:none">
    </span>
    9.1%
   </td>
   <td style="text-align:center;">
    162,000
   </td>
   <td>
    <a href="/wiki/Detroit" title="Detroit">
     Detroit, Michigan
    </a>
   </td>
  </tr>
  <tr>
   <td>
    19
   </td>
   <td>
    <a href="/wiki/Ford_Motor_Company" title="Ford Motor Company">
     Ford Motor
    </a>
   </td>
   <td>
    Automotive
   </td>
   <td style="text-align:center;">
    184,992
   </td>
   <td style="text-align:center;">
    <span typeof="mw:File">
     <span title="Increase">
      <img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/>
     </span>
    </span>
    <span data-sort-value="7000300000000000000♠" style="display:none">
    </span>
    5.0%
   </td>
   <td style="text-align:center;">
    171,000
   </td>
   <td>
    <a href="/wiki/Dearborn,_Michigan" title="Dearborn, Michigan">
     Dearborn, Michigan
    </a>
   </td>
  </tr>
  <tr>
   <td>
    20
   </td>
   <td>
    <a class="mw-redirect" href="/wiki/Anthem_(company)" title="Anthem (company)">
     Elevance Health
    </a>
   </td>
   <td>
    Healthcare
   </td>
   <td style="text-align:center;">
    177,011
   </td>
   <td style="text-align:center;">
    <span typeof="mw:File">
     <span title="Increase">
      <img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/>
     </span>
    </span>
    <span data-sort-value="7000300000000000000♠" style="display:none">
    </span>
    3.3%
   </td>
   <td style="text-align:center;">
    103,679
   </td>
   <td>
    <a href="/wiki/Indianapolis" title="Indianapolis">
     Indianapolis, Indiana
    </a>
   </td>
  </tr>
  <tr>
   <td>
    21
   </td>
   <td>
    <a href="/wiki/Citigroup" title="Citigroup">
     Citigroup
    </a>
   </td>
   <td>
    Financials
   </td>
   <td style="text-align:center;">
    170,757
   </td>
   <td style="text-align:center;">
    <span typeof="mw:File">
     <span title="Increase">

In [6]:
header = table.find_all('th')

In [7]:
title = []
for  head in header:
    name = head.get_text(strip=True)
    title.append(name)

In [8]:
title

['Rank',
 'Name',
 'Industry',
 'Revenue(USD millions)',
 'Revenue growth',
 'Employees',
 'Headquarters']

In [9]:
df = pd.DataFrame(columns=title)
df

Empty DataFrame
Columns: [Rank, Name, Industry, Revenue(USD millions), Revenue growth, Employees, Headquarters]
Index: []

In [10]:
rows = table.find_all("tr")

In [11]:
table_data = []

for row in rows[1:]:  # skip header
    cells = row.find_all("td")
    
    if cells:
        row_data = [cell.get_text(strip=True) for cell in cells]
        table_data.append(row_data)

In [12]:
table_data[:2]

[['1',
  'Walmart',
  'Retail',
  '680,985',
  '5.1%',
  '2,100,000',
  'Bentonville, Arkansas'],
 ['2',
  'Amazon',
  'Retail and cloud computing',
  '637,959',
  '11.0%',
  '1,556,000',
  'Seattle, Washington']]

In [13]:
df = pd.DataFrame(table_data, columns=title)

In [17]:
df.head()

,Rank,Name,Industry,Revenue(USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,"680,985",5.1%,"2,100,000","Bentonville, Arkansas"
1,2,Amazon,Retail and cloud computing,"637,959",11.0%,"1,556,000","Seattle, Washington"
2,3,UnitedHealth Group,Healthcare,"400,278",7.7%,"400,000","Minnetonka, Minnesota"
3,4,Apple,Technology,"391,035",2.0%,"164,000","Cupertino, California"
4,5,CVS Health,Healthcare,"372,809",4.2%,"259,500","Woonsocket, Rhode Island"

In [18]:
df.tail()

,Rank,Name,Industry,Revenue(USD millions),Revenue growth,Employees,Headquarters
95,96,General Dynamics,Aerospace and defense,"47,716",12.9%,"117,000","Reston, Virginia"
96,97,Coca-Cola,Beverage,"47,061",2.9%,"69,700","Atlanta, Georgia"
97,98,TIAA,Financials,"46,946",2.6%,"15,623","New York City, New York"
98,99,Travelers,Insurance,"46,423",12.2%,"34,000","New York City, New York"
99,100,Eli Lilly,Pharmaceutical,"45,043",32.0%,"47,000","Indianapolis, Indiana"

In [19]:
df.to_csv("company_revenue.csv", index=False)